#!/bin/bash

# install_script: automatically symlinks all the dotfiles installed from git. Also backs up old dotfiles in ~/old_dotfiles

dotfiles=~/dotfiles
old_dotfiles=~/old_dotfiles

files=(bashrc vimrc sh.vim tex.vim py.vim text.vim preamble.tex code.tex pgfplotsitablecsv.tex)

mkdir -p ${old_dotfiles}

while read filename; do
  if [[ -f $filename ]]; then
    mv $filename $old_dotfiles
  fi
done < ~/dotfiles/destinations

mkidr -p ~/.vim/ftplugin ~/.vim/snippets ~/.vim/bundle

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

i=0
while read destination; do
  ln -s ${dotfiles}/${files[$i]} $destination
  i=$((i+1))
done < ~/dotfiles/destination



