#!/bin/bash

# install_script: automatically symlinks all the dotfiles installed from git. Also backs up old dotfiles in ~/old_dotfiles

read -p "For all config files to work, you have to have vim zsh oh-my-zsh i3-gaps compton installed. All installed [Y|N]?" answer

dotfiles=~/dotfiles
old_dotfiles=~/old_dotfiles

files=(bashrc vimrc sh.vim tex.vim py.vim text.vim preamble.tex code.tex pgfplotstablecsv.tex zshrc compton.conf config i3status.conf)
destinations=(~/.bashrc ~/.vimrc ~/.vim/ftplugin/sh.vim ~/.vim/ftplugin/tex.vim ~/.vim/ftplugin/py.vim ~/.vim/ftplugin/text.vim ~/.vim/snippets/preamble.tex ~/.vim/snippets/code.tex ~/.vim/snippets/pgfplotstablecsv.tex ~/.zshrc ~/.compton.conf ~/.config/i3/config ~/.config/i3/i3status.conf)

if [[ "$answer" =~  [Y.*|y.*] ]]; then
  mkdir -p ${old_dotfiles}

  for filename in ${destinations[@]}; do
    if [[ -f "$filename" ]]; then
      mv "$filename" $old_dotfiles
    fi
  done

  mkdir -p ~/.vim/ftplugin ~/.vim/snippets ~/.vim/bundle

  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

  i=0
  for destination in ${destinations[@]}; do
    echo ${dotfiles}/${files[$i]} "$destination"
    ln -s ${dotfiles}/${files[$i]} "$destination"
    i=$((i+1))
  done
else 
  exit 1
fi



